// investor-invest.js — REWRITTEN for Aurora PostgreSQL via RDS Data API
// Route: POST /investor/invest
// Body:  { "deal_id": "abc123", "amount": 250 }

const { RDSDataClient, ExecuteStatementCommand } = require("@aws-sdk/client-rds-data");
const { requireAuth, jsonResponse } = require("./auth");

const rds = new RDSDataClient({});
const CLUSTER_ARN = process.env.DB_CLUSTER_ARN;
const SECRET_ARN = process.env.DB_SECRET_ARN;
const DATABASE_NAME = process.env.DB_NAME || "postgres";
const MIN_INVESTMENT = 100;

async function runSql(sql, parameters = []) {
  const command = new ExecuteStatementCommand({
    resourceArn: CLUSTER_ARN,
    secretArn: SECRET_ARN,
    database: DATABASE_NAME,
    sql,
    parameters,
    formatRecordsAs: "JSON",
  });
  const response = await rds.send(command);
  return response.formattedRecords ? JSON.parse(response.formattedRecords) : [];
}

exports.handler = async (event) => {
  let claims;
  try {
    claims = await requireAuth(event);
  } catch (e) {
    return jsonResponse(e.statusCode || 401, { error: e.message });
  }

  let body;
  try {
    body = JSON.parse(event.body || "{}");
  } catch (e) {
    return jsonResponse(400, { error: "Invalid JSON body" });
  }

  const { deal_id, amount } = body;
  if (!deal_id || typeof amount !== "number") {
    return jsonResponse(400, {
      error: "deal_id (string) and amount (number) are required",
    });
  }
  if (amount < MIN_INVESTMENT) {
    return jsonResponse(400, { error: `Minimum investment is £${MIN_INVESTMENT}` });
  }

  // Load the deal to validate it.
  const deals = await runSql(
    `SELECT id, status, funding_goal, funding_raised FROM deals WHERE id = :id`,
    [{ name: "id", value: { stringValue: deal_id } }]
  );
  const deal = deals[0];
  if (!deal) {
    return jsonResponse(404, { error: "Deal not found" });
  }
  if (deal.status !== "active") {
    return jsonResponse(400, {
      error: `Deal is not open for investment (status: ${deal.status})`,
    });
  }

  const goal = parseFloat(deal.funding_goal) || 0;
  const raised = parseFloat(deal.funding_raised) || 0;
  if (goal > 0 && raised + amount > goal) {
    return jsonResponse(400, {
      error: `This investment would exceed the funding goal. £${(goal - raised).toFixed(2)} remaining.`,
    });
  }

  // Insert the investment record (investment_id auto-generated by Postgres).
  const inserted = await runSql(
    `INSERT INTO investments (investor_id, investor_email, deal_id, amount, status)
     VALUES (:investor_id, :investor_email, :deal_id, :amount, 'confirmed')
     RETURNING investment_id, status`,
    [
      { name: "investor_id", value: { stringValue: claims.sub } },
      { name: "investor_email", value: { stringValue: claims.email || "" } },
      { name: "deal_id", value: { stringValue: deal_id } },
      { name: "amount", value: { doubleValue: amount } },
    ]
  );

  // Bump the deal's funding_raised.
  await runSql(
    `UPDATE deals SET funding_raised = funding_raised + :amount WHERE id = :id`,
    [
      { name: "amount", value: { doubleValue: amount } },
      { name: "id", value: { stringValue: deal_id } },
    ]
  );

  return jsonResponse(200, {
    investment_id: inserted[0].investment_id,
    status: inserted[0].status,
    deal_id,
    amount,
  });
};
